<div align="center"><img src="Layout/GetHeadline.php5" alt="Üba uns"></div>
<br><br>
Oft wurde in Unterneukirchen schon davon geredet einen Burschenverein zu gründen, da noch eine gut erhaltene Fahne des kath. Burschenvereins Unterneukirchen aus früheren Zeiten vorhanden ist. Ein paar junge Burschen (Erich Zwirglmaier, Seppe Jetzlsperger, Josef Langlechner (hoal), Andreas Mayr und Christoph Kainzmaier) machten sich im September 2006 auf dem Weg nach Surheim, denn hier wurde im Jahr 2005 ein Burschenverein wieder gegründet, und das große Wiedergründungsfest wurde 2006 im September gefeiert. Bereits nach kurzer Zeit war uns allen klar "Unterneukirchen braucht an Burschenverein&#147;. In Surheim wurde bereits mit vielen anderen Burschenvereinen "geratscht" und wir informierten uns über die ganzen Tätigkeiten, die ein Burschenverein über das ganze Jahr hinweg so macht.
<br><br>
Im Frühjahr 2007 war dann ein erstes zusammentreffen bei dem dann noch Konrad Mitterreiter und Markus Perschl hinzukamen, die auch vollstens davon überzeugt waren, dass ein Burschenverein gegründet werden muss. Am 30.03.2007 war es dann soweit, es trafen sich im Gasthaus Raspl 14 junge Burschen und der Verein wurde im kleinen Kreis mit Pfarrer Hr. Schauer und Bürgermeister Hr. Heindl gegründet. Der kath. Burschenverein hat sich zum Ziel gesetzt, die Förderung und den Erhalt der Geselligkeit und der Tradition in Unterneukirchen, sowie den Kontakt zwischen den Burschen zu pflegen. Auf der Grundlage von Kameradschaft und Zusammenhalt sollen durch den Verein alte Heimatbräuche aufgegriffen und gefördert, und dadurch der Zusammenhalt der Jugend in der Gemeinde gestärkt und dem Verfall des ländlichen Brauchtums und Lebens Einhalt geboten werden.
<br><br>
Ein paar Tage später, wurde dann ein Infoabend sowie 1. Mitgliedsversammlung abgehalten, wo sich jeder Interessent über den Burschenverein Informieren konnte. Jedes Mitglied das bis zur 1. Mitgliedsversammlung beigetreten ist, zählt zu den Gründungsmitgliedern. Der neugegründete Verein konnte sogar die historische Marke aus dem Jahr 1914 übertrumpfen, denn bei der 1. Gründung des kath. Burschenvereins 1914 tragen 53 Mitglieder bei. Aktuell hat der Verein bereits über 90 Mitglieder.
<br><br>
Der Verein beteiligt sich bei Kirchlichen so wie weltlichen Festen. Ein erster Höhepunkt in der jungen Vereinsgeschichte war die "Burschenversteigerung" auf der Unterneukirchner Hof-Dult mit dem Auktionatr Adi Hager.
<br><br>
Wenn Sie unsere Ziele unterstützen möchten, würden wir uns über Ihre Mitarbeit freuen. Selbstverständlich freuen wir uns auch über eine kleine Spende, noch mehr würden wir es für gut heißen, wenn sie uns aktiv als Mitglied unterstützen!